#!/usr/bin/bash

# Usage: ~/GitHub/geco-bern/rsofun_doc/analysis/run_predictions2.sh <SCENARIO> <NRUNS> <NBURNIN> <NPREDICTIONS> <NERRORS> <SUFFIX>
SCENARIO="${1}"
NRUNS="${2:-100000}"    # default after '-'
NBURNIN="${3:-30000}"   # default after '-'
NPREDICTIONS="${4:-20}" # default after '-'
NERRORS="${5:-3}"       # default after '-'
SUFFIX="${6:-_continued.rds}" # default after '-'

# OUTFILE="${1:-run_predictions_autogenerated.sh}"
OUTFILE="GitHub/geco-bern/rsofun_doc/analysis/run_predictions_autogenerated.sh"


cat > "$OUTFILE" <<EOF
#! /usr/bin/bash -l
#SBATCH --job-name="pred_s${SCENARIO}_${NRUNS}-${NBURNIN}-req${NPREDICTIONS}-${NERRORS}"
#SBATCH --time=48:30:00
#SBATCH --partition=icpu-stocker
#SBATCH --array=${SCENARIO}
#SBATCH --cpus-per-task=9
#SBATCH --mem-per-cpu=8G
#SBATCH --mail-user=your.email@unibe.ch
#SBATCH --mail-type=none
#SBATCH --chdir=GitHub/geco-bern/rsofun_doc
#SBATCH --output=slurm-logs/slurm-%x.%j.txt  ###S-B-A-T-C-H --error=slurm-logs/slurm-%x.%j_err.txt

export SBATCH_EXPORT=NONE
export SLURM_EXPORT_ENV=ALL

echo "Started on: \$(date --rfc-3339=seconds)"
echo "Hostname: \$(hostname)"
echo "Working directory: \$PWD"

module load GEOS/3.12.2-GCC-13.3.0
module load PROJ/9.4.1-GCCcore-13.3.0
module load GDAL/3.10.0-foss-2024a
module load UDUNITS/2.2.28-GCCcore-13.3.0
module load SQLite/3.45.3-GCCcore-13.3.0
module load CMake/3.29.3-GCCcore-13.3.0
module load GCC/13.3.0
module load libxml2/2.12.7-GCCcore-13.3.0
module load R/4.4.2-gfbf-2024a

NRUNS=${NRUNS}                # which MCMC sampling to use
NBURNIN=${NBURNIN}            # how many MCMC samples to discard (in each chain)
NPREDICTIONS=${NPREDICTIONS}  # how many samples of posterior to use for predictions
NERRORS=${NERRORS}            # how many samples of structural error
SUFFIX=${SUFFIX}

Rscript analysis/04_make-test-train_predictions.R "out_calib__scen${SCENARIO}_DREAMzs-\${NRUNS}-0iter_8x3chains_on_CPU8x1\${SUFFIX}" "\${NBURNIN}" "\${NPREDICTIONS}" "8" "\${NERRORS}"

echo "Finished on: \$(date --rfc-3339=seconds)"
EOF

#chmod +x "$OUTFILE"
echo "SLURM batch script generated and submitted at: $OUTFILE"
sbatch $OUTFILE
